services:
  avatar.service.db:
    container_name: postgres_container
    image: docker.io/library/postgres:latest 
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: docker.io/dpage/pgadmin4:latest 
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.58.0
    ports:
      - "16686:16686" # Jaeger Web UI
      - "4317:4317"   # OTLP 